---
functional:
  - Пользователь должен иметь возможность создавать аккаунт
  - Пользователь должен иметь возможность создавать аккаунт через GitHub
  - Пользователь должен иметь возможность создавать аккаунт через Discord
  - Пользователь должен иметь возможность входить в систему и выходить из неё (login/logout)
  - Пользователь должен иметь возможность входить в систему через GitHub
  - Пользователь должен иметь возможность входить в систему через Discord
  - Пользователь должен иметь возможность восстановить пароль
  - Пользователь должен иметь возможность создавать пробную игру (без еффекта на его рейтинг)
  - Пользователь должен иметь возможность создавать новую игру
  - Пользователь должен иметь возможность выбирать уровень сложности
  - Пользователь должен иметь возможность приглашать друга из списка
  - Пользователь должен иметь возможность приглашать друга по ссылке
  - Пользователь должен иметь возможность во время матча видеть редактор кода
  - Пользователь должен иметь возможность видеть вывод тестов
  - Пользователь может следить за ходом чужих матчей в режиме реального времени
  - Пользователь должен иметь возможность менять язык во время матча
  - Пользователь должен иметь возможность создавать турнир
  - Пользователь должен иметь возможность вступать в турнир
  - Пользователь должен иметь возможность вступать в клан
  - Пользователь должен иметь возможность наблюдать за игрой других пользователей
  - Пользователь должен иметь возможность использовать чат внутри игры в режими реального времени
  - Пользователь должен иметь возможность отправлять приглашения на игру через чат 
  - Пользователь должен иметь возможность просматривать завершённые игры 
  - Пользователь должен иметь возможность редактировать свой профиль
  - После прохождения игры пользователь должен иметь возможность проиграть игру в проигрыватели
  - Каждый пользователь должен иметь возможность просмотреть посчитанные очки и свой рейтинг в таблицах за неделю, за месяц и за всё время
non-functional:
  - Сайт должен корректно отображаться в последних версиях популярных браузеров
  - Сайт должен корректно отображаться на мобильных устройствах
  - Задачи игр должны иметь полную поддержку русского языка
  - Задачи игр должны иметь полную поддержку английского языка
  - Интерфейс должен поддерживать пагинацию или бесконечную прокрутку в списках рейтингов
implicit:
  - Документация (wiki) должна поддерживаться в актуальном состоянии
  - Сообщество взаимодействует через Telegram-канал и GitHub Issues для обсуждения фич и отчётов об ошибках
  - Проект предусматривает возможность разработки и поддержки Chrome-extension, интегрирующегося с основным сайтом
