---
functional:
  - Пользователь должен иметь возможность создавать аккаунт
  - Пользователь должен иметь возможность входить в систему и выходить из неё (login/logout)
  - Пользователь должен иметь возможность восстановить пароль
  - Пользователь должен иметь возможность сменить пароль
  - Пользователь должен иметь возможность создавать игру
  - Пользователь должен иметь возможность выбирать уровень сложности
  - Пользователь должен иметь возможность приглашать друга или бота по ссылке
  - Пользователь должен иметь возможность во время матча видеть редактор кода
  - Пользователь должен иметь возможность видеть вывод тестов
  - Пользователь должен иметь возможность менять язык во время матча
  - Пользователь может следить за ходом чужих матчей в режиме реального времени
  - Пользователь должен иметь возможность использовать чат внутри игры в режими реального времени
  - После прохождения игры пользователь должен иметь возможность проиграть игру в проигрыватели
  - Каждый пользователь должен иметь возможность просмотреть посчитанные очки и свой рейтинг в таблицах: за неделю, за месяц и за всё время
non-functional:
  - API должен отвечать за ≤200 мс при обычной нагрузке, нагрузочное тестирование до 1000 одновременных пользователей.
  - Сайт должен корректно отображаться в последних версиях популярных браузеров
  - Сайт должен корректно отображаться на мобильных устройствах
  - Система должна шифровать пользовательские данные при передаче и хранении
  - Сайт должен иметь полную поддержку русского языка
  - Сайт должен иметь полную поддержку английского языка
implicit:
  - Документация (wiki) должна поддерживаться в актуальном состоянии
  - Сообщество взаимодействует через Telegram-канал и GitHub Issues для обсуждения фич и отчётов об ошибках
  - Проект предусматривает возможность разработки и поддержки Chrome-extension, интегрирующегося с основным сайтом
