---
functional:
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность зарегистрироваться через GitHub
  - Пользователь должен иметь возможность зарегистрироваться через Discord
  - Пользователь должен иметь возможность входить в систему и выходить из неё
  - Пользователь должен иметь возможность входить в систему через GitHub
  - Пользователь должен иметь возможность входить в систему через Discord
  - Пользователь должен иметь возможность восстановить пароль
  - Пользователь должен иметь возможность создавать пробную игру (без влияния на рейтинг)
  - Пользователь должен иметь возможность создавать новую игру
  - Пользователь должен иметь возможность выбирать уровень сложности
  - Пользователь должен иметь возможность приглашать друга из списка
  - Пользователь должен иметь возможность приглашать друга по ссылке
  - Пользователь должен иметь возможность видеть редактор кода во время матча
  - Пользователь должен иметь возможность видеть вывод тестов
  - Пользователь должен иметь возможность следить за ходом чужих матчей в режиме реального времени
  - Пользователь должен иметь возможность менять язык интерфейса во время матча
  - Пользователь должен иметь возможность создавать турнир
  - Пользователь должен иметь возможность вступать в турнир
  - Пользователь должен иметь возможность вступать в клан
  - Пользователь должен иметь возможность наблюдать за игрой других пользователей
  - Пользователь должен иметь возможность использовать чат внутри игры в режиме реального времени
  - Пользователь должен иметь возможность отправлять приглашения на игру через чат
  - Пользователь должен иметь возможность просматривать завершённые игры
  - Пользователь должен иметь возможность редактировать свой профиль
  - Пользователь должен иметь возможность просматривать повторное проигрывание игры после её завершения
  - Пользователь должен иметь возможность просматривать начисленные очки и свой рейтинг в таблицах за неделю, за месяц и за всё время

non-functional:
  - Сайт должен корректно отображаться в последних версиях основных браузеров
  - Сайт должен корректно отображаться на мобильных устройствах
  - Игровые задания должны полностью поддерживать русский язык
  - Игровые задания должны полностью поддерживать английский язык
  - Интерфейс должен поддерживать пагинацию или бесконечную прокрутку на страницах рейтингов

implicit:
  - Документация (Wiki) должна постоянно поддерживаться в актуальном состоянии
  - Сообщество взаимодействует через Telegram-канал и GitHub Issues для обсуждения функциональных возможностей и отчётов об ошибках
  - Проект предусматривает возможность разработки и поддержки расширения для Chrome, интегрирующегося с основным сайтом
